DROP TABLE IF EXISTS Follow CASCADE;
DROP TABLE IF EXISTS Playback CASCADE;
DROP TABLE IF EXISTS PlaylistSong CASCADE;
DROP TABLE IF EXISTS Playlist CASCADE;
DROP TABLE IF EXISTS Song CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS Listener CASCADE;